// TypeScript declarations for api.js
export function getHomePlots(limit?: number, cursor?: string): Promise<any>;
export function getSpecialCuration(): Promise<any>;
export function getBanners(): Promise<any>;
export function getPopups(): Promise<any>;
export function getFeatureFlag(name: string): Promise<any>;
export function getGenresRanking(): Promise<any>;
export function getRanking(type?: string, limit?: number, filterValues?: string): Promise<any>;
export function getPlot(plotId: string): Promise<any>;
export function getPlotImages(plotId: string): Promise<any>;
export function getCharacterImages(plotId: string, characterId: string): Promise<any>;
export function getSimilarPlots(plotId: string, limit?: number): Promise<any>;
export function getLikedPlots(limit?: number): Promise<any>;
export function getActiveRoomId(plotId: string): Promise<any>;
export function createRoom(plotId: string): Promise<any>;
export function getRooms(limit?: number): Promise<any>;
export function getRoom(roomId: string): Promise<any>;
export function deleteRoom(roomId: string): Promise<any>;
export function getRoomModelSetting(roomId: string): Promise<any>;
export function getRoomCyoaSetting(roomId: string): Promise<any>;
export function getIntroBeforeSelection(roomId: string): Promise<any>;
export function createIntro(roomId: string): Promise<any>;
export function getSelectedPersona(plotId: string, roomId: string): Promise<any>;
export function getMessages(roomId: string, limit?: number): Promise<any>;
export function getMessagesByCursor(roomId: string, cursor: string, limit?: number): Promise<any>;
export function sendMessageStream(roomId: string, text: string, onEvent: (event: any) => void, onDone: () => void, retry?: boolean): Promise<void>;
export function regenMessageStream(roomId: string, messageId: string, onEvent: (event: any) => void, onDone: () => void, retry?: boolean): Promise<void>;
export function getCandidates(roomId: string, messageId: string, limit?: number): Promise<any>;
export function selectCandidate(roomId: string, messageId: string, candidateId: string): Promise<any>;
export function editMessage(roomId: string, messageId: string, candidateId: string, text: string): Promise<any>;
export function deleteMessages(roomId: string, messageId: string): Promise<any>;
export function getRecommended(roomId: string): Promise<any>;
export function refreshRecommended(roomId: string): Promise<any>;
export function getRecommendQuota(): Promise<any>;
export function getCoinBalance(): Promise<any>;
export function getCoinAutoPaymentSettings(): Promise<any>;
export function getCreatorStats(): Promise<any>;
export function getZetaPassSubscription(): Promise<any>;
export function getZetaPassPromotionEligibility(): Promise<any>;
export function getZetaPassProConversionStatus(): Promise<any>;
export function getLatestNotificationTime(): Promise<any>;
export function getAppPushSetting(type?: string): Promise<any>;
export function getStoreProducts(productType: string): Promise<any>;
export function getSessionOverview(): Promise<any>;
export function getUserChatProfiles(limit?: number, options?: { plotId?: string; roomId?: string }): Promise<any>;
export function createUserChatProfile(data: { name: string; description?: string }): Promise<any>;
export function checkUserChatProfileAbuse(data: { name: string; description?: string }): Promise<any>;
export function updateUserChatProfile(profileId: string, data: { name: string; description?: string }): Promise<any>;
export function deleteUserChatProfile(profileId: string): Promise<any>;
export function selectUserChatProfile(profileId: string, options?: { plotId?: string; roomId?: string }): Promise<any>;
export function getQuiz(): Promise<any>;
export function joinQuiz(quizId: string, plotId: string): Promise<any>;
export function claimQuiz(quizId: string): Promise<any>;