// Fetches the latest version of com.scatterlab.messenger from Google Play
// and writes it to src/lib/version.ts
import { writeFileSync, existsSync } from "node:fs"
import { resolve, dirname } from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUT = resolve(__dirname, "..", "src", "lib", "version.ts")
const FALLBACK = "0.0.1"

let version = FALLBACK

try {
  const gplay = await import("google-play-scraper")
  const app = await gplay.default.app({ appId: "com.scatterlab.messenger" })
  version = app.version || FALLBACK
  console.log(`[fetch-version] Fetched: com.scatterlab.messenger v${version}`)
} catch (err) {
  console.warn(`[fetch-version] Failed to fetch from Google Play: ${err.message}`)
  if (existsSync(OUT)) {
    // Keep cached version
    console.log("[fetch-version] Using cached version.ts")
    process.exit(0)
  }
  console.log(`[fetch-version] Using fallback version: ${FALLBACK}`)
}

writeFileSync(OUT, `// Auto-generated by scripts/fetch-version.mjs — do not edit manually
export const APP_VERSION = ${JSON.stringify(version)}
`, "utf-8")
console.log(`[fetch-version] Wrote ${OUT} (v${version})`)
